#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/lmgr
#
# IDENTIFICATION
#    src/backend/storage/lmgr/Makefile
#
#-------------------------------------------------------------------------

subdir = contrib/gdd_test

top_builddir = ../..

include $(top_builddir)/src/Makefile.global
include $(top_builddir)/contrib/contrib-global.mk

CFLAGS += $(CFLAGS_SL)

SHARED_OBJ = external_lock_test.so gdd_test_external_lock.so

OBJS = external_lock_test.o gdd_test_external_lock.o

# gdd_test_external_lock.o: gdd_test_external_lock.c
# $(CC) $(CFLAGS) $(CFLAGS_SL) $(CPPFLAGS) gdd_test_external_lock.c -c
	

include $(top_srcdir)/src/backend/common.mk

ifdef TAS
TASPATH = $(top_builddir)/src/backend/port/tas.o
endif

s_lock_test: s_lock.c $(top_builddir)/src/port/libpgport.a
	$(CC) $(CPPFLAGS) $(CFLAGS) -DS_LOCK_TEST=1 $(srcdir)/s_lock.c \
		$(TASPATH) -L $(top_builddir)/src/port -lpgport -o s_lock_test

# see notes in src/backend/parser/Makefile
lwlocknames.c: lwlocknames.h
	touch $@

lwlocknames.h: $(top_srcdir)/src/backend/storage/lmgr/lwlocknames.txt generate-lwlocknames.pl
	$(PERL) $(srcdir)/generate-lwlocknames.pl $<

check: s_lock_test
	./s_lock_test

clean distclean:
	rm -f s_lock_test

maintainer-clean: clean
	rm -f lwlocknames.h lwlocknames.c
